-- MySQL Script generated by MySQL Workbench
-- Tue Jul 19 20:53:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ugel_rd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ugel_rd` ;

-- -----------------------------------------------------
-- Schema ugel_rd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ugel_rd` DEFAULT CHARACTER SET utf8 ;
USE `ugel_rd` ;

-- -----------------------------------------------------
-- Table `ugel_rd`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ugel_rd`.`personal` (
  `id_personal` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL,
  `apellido_pat` VARCHAR(45) NULL,
  `dni` VARCHAR(45) NULL,
  PRIMARY KEY (`id_personal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ugel_rd`.`tipo_resolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ugel_rd`.`tipo_resolucion` (
  `id_tipo_resolucion` INT NOT NULL AUTO_INCREMENT,
  `detalle` VARCHAR(100) NULL,
  PRIMARY KEY (`id_tipo_resolucion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ugel_rd`.`resolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ugel_rd`.`resolucion` (
  `id_resolucion` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `doc_url` VARCHAR(45) NULL,
  `id_personal` INT NOT NULL,
  `id_tipo_resolucion` INT NOT NULL,
  `numero_res` VARCHAR(45) NULL,
  PRIMARY KEY (`id_resolucion`),
  CONSTRAINT `fk_resolucion_personal`
    FOREIGN KEY (`id_personal`)
    REFERENCES `ugel_rd`.`personal` (`id_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resolucion_tipo_resolucion1`
    FOREIGN KEY (`id_tipo_resolucion`)
    REFERENCES `ugel_rd`.`tipo_resolucion` (`id_tipo_resolucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ugel_rd`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ugel_rd`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ugel_rd`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ugel_rd`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `ugel_rd`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
